#!/bin/bash

main()
{
  parse_arguments "$@"
  hyprctl switchxkblayout current next
}

help()
{
  cat "$(dirname "$0")/doc/$(basename "$0").help"
}

print_error()
{
  echo "$(basename "$0"): $1"
}

parse_arguments()
{
  while (( $# > 0 ))
  do
    case "$1" in
      -h | --help)
        help
        exit 0
        ;;
    esac
  done
}

main "$@"
